version: '3.8'
services:
  db:
    image: postgres:13.0-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./db_schema.sql:/docker-entrypoint-initdb.d/1-init.sql
    env_file:
      - .env

#    ports:
#      - 5432:5432
    networks:
      - app-network

  es:
    image: elasticsearch:7.16.3
    restart: always
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    depends_on:
      - db
    networks:
      - app-network

  etl:
    build: ./etl
    command: python main.py
    restart: always
    env_file:
      - .env
    volumes:
      - ./etl/:/etl
      - .cache/pip-docker/:/root/.cache/pip
    depends_on:
      - es
      - db
    networks:
      - app-network


volumes:
  postgres_data:
  es_data:

networks:
    app-network:
        driver: bridge